### ISSUE TITLE
Founder's Alpha Patch

### ISSUE THREAD

**Issue by nmclifford** [PhoenixLabsCanada/status-page#9]
We are working around the clock to release a patch for the Founder's Alpha, including many fixes to a variety of issues.  For the full breakdown, please visit this [forum thread](https://forums.playdauntless.com/t/founders-alpha-8-19-2017-patch-notes-updated/123723)

**Comment by PHXcrash7800** [comment]
Dauntless servers will be down for one hour while we patch the game. You can read about this update in the Patch Notes & Updates section of the Forums.

**Comment by ereidphx** [comment]
Patching is concluded. Slay on!
